vich_uploader:
    db_driver: orm
    metadata: 
        type: attribute

    mappings:
        projet_image:
            uri_prefix: /images/projets/principale
            upload_destination: '%kernel.project_dir%/public/images/projets/principale'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        projet_apercu:
            uri_prefix: /images/projets/apercu
            upload_destination: '%kernel.project_dir%/public/images/projets/apercu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        techno_image:
            uri_prefix: /images/technos
            upload_destination: '%kernel.project_dir%/public/images/technos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        certification_image:
            uri_prefix: /images/certifications
            upload_destination: '%kernel.project_dir%/public/images/certifications'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer