public_controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_controllers:
    resource:
        path: ../src/Controller/Admin
        namespace: App\Controller\Admin
    prefix: 'admin'
    type: attribute

delete:
    path: delete/{id}
    controller: App\Controller\Admin\ProjetsController
    methods: ["POST"]

fiche_popup:
    path: '/projet/{id}/fiche_projet'
    controller: 'App\Controller\ProjetController\fichePopup'